

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.pylint.messages_control]
max-line-length = 120
disable = [
  "missing-docstring",
  "logging-fstring-interpolation",
  "too-many-arguments",
  "too-many-locals",
]
good-names=[
    "i",
    "j",
    "k",
    "x",
    "db",
]

